### ISSUE TITLE
Reflow after resizing

### ISSUE THREAD

**Issue by ralsina** [kalyan02/flowr-js#3]
In mobile devices, the page width changes when the device rotates, so the image layout is now wrong.

How would it be possible to reflow in that case? I tried doing something like

```
$(window).on('resize', function () {
    $("#gallery_container").flowr();
});
```

with and without passing the whole data structure as argument to flowr() but it doesn't seem to work.

Any hints?

**Comment by kalyan02** [comment]
Am working on a fix for issue #2 which should fix this too.

**Comment by ralsina** [comment]
@kalyan02 awesome!

**Comment by kalyan02** [comment]
This is fixed and is available on master. the layout is set to be responsive by default.
To disable responsiveness you can set the flag `responsive:false`

```
$("#...").flowr({
    .....
    responsive : false
});
```

Please feel free to report any issues you may face. I will be happy to help.

**Comment by ralsina** [comment]
AWESOME! Thanks a lot!

**Comment by max-arnold** [comment]
With `responsive: true` I'm seeing gallery duplication and high cpu usage upon resize. For more info see https://github.com/ralsina/nikola/issues/687

Setting `responsive: false` fixes it.

**Comment by sakitume** [comment]
Hello. I am also seeing this issue with gallery duplication upon resize. It would be great if I didn't have to set `responsive: false` to work around this bug.

**Comment by kalyan02** [comment]
I disabled it temporarily, until I find a permanent solution.
